
name: npm publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
        registry-url: https://registry.npmjs.org/

    - uses: calcit-lang/setup-cr@0.0.3
      with:
        version: "0.9.0-a1"

    - run: yarn && caps --ci && cr -1 js

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
